setwd("/Users/cherry/Data/course4week1")
data <- read.table("household_power_consumption.txt", sep = ";", header=TRUE, na.strings= "?")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
power <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
power$Time <- strptime(paste(power$Date, power$Time), format = "%Y-%m-%d %H:%M:%S")
par(mar = c(4,4,2,1))
plot(x=power$Time, y=power$Global_active_power, type = "l", lty =1, ylab = "Global Active Power (kilowatts)", xlab = "")
dev.copy(png, "plot2.png")
dev.off()